users:
  - name: 强子
    token_env: USER1_TOKEN
    device_id: device_id_1
    digital_life_id: 4aba5d0c-2ea6-4e11-b9a8-f754ca537cd7

  - name: 彭伟
    token_env: USER2_TOKEN
    device_id: device_id_2
    digital_life_id: feb8fd06-3ec3-43e8-baa2-d45bb829d0d3

  - name: 雁青
    token_env: USER3_TOKEN
    device_id: device_id_3
    digital_life_id: feb8fd06-3ec3-43e8-baa2-d45bb829d0d3
