name: Daily SMS Task

# 定时触发和手动触发
on:
  schedule:
    - cron: '04 04 * * *'   # UTC 时间对应北京时间中午 12 点
  workflow_dispatch:        # 允许手动触发

jobs:
  run-sms:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 执行 SMS 脚本
        run: python send_sms.py
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
